accounts/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from .api_view import *
from django.conf import settings
from django.conf.urls.static import static
app_name='accounts'


urlpatterns = [
    # path('signup',views.signup ,name='signup'),
    # path('signin',views.signin ,name='signin'),
    path('login/',views.signup,name='login'),
    path('activate_account/<uidb64>/<token>/', views.activate_account, name='activate'),
    path('log_out',views.log_out ,name='log_out'),
    path('password_reset/',views.password_reset ,name='password_reset'),
    path('password_change/<slug:slug>',views.password_change ,name='password_change'),
    path('password_reset_set/<uidb64>/<token>/',views.password_reset_set ,name='password_reset_set'),
    path('profile/<slug:slug>',views.profile ,name='profile'),
    path('profile/<slug:slug>/editprofile',views.edit_profile ,name='edit'),
    
    
    
    
    # api
    # path('user/list',UserViewSet.as_view({'get': 'list'}))c,
    path('api/register',RegisterUserAPIView.as_view()),
    path('api/login',LoginView.as_view(),name='login_api'),
    path('api/profile/<slug:slug>',ProfileAPi.as_view()),
    path('api/profile/<slug:slug>/editprofile',ProfileAPIUpdate.as_view()),
    path('api/password_reset', password_reset.as_view(), name='password_reset'),
    path('api/password_reset_set/<uidb64>/<token>/', password_reset_set.as_view(), name='password_reset_set'),
    
    
    # path('user/list',PropertyAPiList.as_view(),name='PropertyAPiList'),
    
    
    # path('remove_myresevation/<int:resevation_id>',views.remove_myresevation ,name='remove_myresevation'),
    # path('remove_mylisting/<int:property_id>',views.remove_mylisting ,name='remove_mylisting'),
]

chat/urls.py
from django.urls import path 
from .views import *
from . import views
# from.api_view import *
app_name='chat'


urlpatterns = [
    path('',views.home,name='home'),
    path('chat/',views.main,name='main'),
    path('chat_details/<slug:slug>',views.chat_details,name='chat_details'),
    path('send_message/<slug:slug>',views.send_message,name='send_message'),
    path('receive_message/<slug:slug>',views.receive_message,name='receive_message'),
    path('friend_request/<slug:slug>',views.friend_request,name='friend_request'),
    path('add_friend/',views.add_friend,name='add_friend'),
    path('send_request/<slug:slug>',views.send_request,name='send_request'),
    path('accecpt_friend_request/<slug:slug>',views.accecpt_friend_request,name='accecpt_friend_request'),
    # path('hotel/',PropertyList.as_view(),name='property_list'),
    # path('hotel/<slug:slug>',PropertyDetail.as_view(),name='property_detail'),
    # path('create/',PropertyCreate.as_view(),name='property_create'),
    
    
    # # api
    # path('property/list',PropertyAPiList.as_view(),name='PropertyAPiList'),
    # path('property/list/<int:pk>',PropertyAPiDetail.as_view(),name='PropertyAPiDetail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('chat.urls' ,namespace='chat')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    
    
    path('api-auth/', include('rest_framework.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from accounts.models import Profile
# Create your models here.
from datetime import datetime
from django.utils.translation import gettext_lazy as _
class ChatMessage(models.Model):
    body = models.TextField()
    msg_sender = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='msg_sender')
    msg_receiver = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='msg_receiver')
    seen=models.BooleanField(default=False)
    send_in = models.DateTimeField(verbose_name=_("Time Send"), default=datetime.now)

    def __str__(self):
        return self.body

    def __unicode__(self):
        return 

chat/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse
from accounts.models import Profile,Friend
# Create your views here.
from django.shortcuts import get_object_or_404
from.models import ChatMessage
from django.db.models import Q
from itertools import chain
from django.urls import reverse
import json

def home(request):
    if request.user.is_authenticated:
        return redirect('/chat')
    return render(request,'chat/index.html',)

def main(request):
    profile = get_object_or_404(Profile, user=request.user)
    friends = profile.friend.all()
    return render(request,'chat/chat.html',{'profile': profile, 'friends': friends})

def chat_details(request,slug):
    profile=get_object_or_404(Profile,slug=slug)
    user_profile = get_object_or_404(Profile, user=request.user)
    msg_sender = ChatMessage.objects.filter(
        (Q(msg_sender=profile) & Q(msg_receiver=user_profile))
    ).order_by('send_in')
    msg_receiver = ChatMessage.objects.filter(
        (Q(msg_sender=user_profile) & Q(msg_receiver=profile))
    ).order_by('send_in')
    all_messages = sorted(chain(msg_sender, msg_receiver), key=lambda x: x.send_in)
    if request.method == 'POST' and 'send' in request.POST:
        chat_body = request.POST['chat_body']
        chat_text=ChatMessage.objects.create(
                                        msg_sender=user_profile,
                                        body=chat_body,
                                        msg_receiver=profile,
                                            )
        chat_text.save()
        return redirect(reverse('chat:chat_details', kwargs={'slug': profile.slug}))



    return render(request,'chat/chat_details.html',{'profile': profile,'user_profile': user_profile,'all_messages': all_messages})

def send_message(request,slug):
    profile=get_object_or_404(Profile,slug=slug)
    user_profile = get_object_or_404(Profile, user=request.user)
    data=json.loads(request.body)
    chat_body = data["msg"]
    chat_text=ChatMessage.objects.create(
                                        msg_sender=user_profile,
                                        body=chat_body,
                                        msg_receiver=profile,
                                            )
    chat_text.save()
    response_data = {
        'msg': chat_body,
        'send_in': chat_text.send_in,  # Assuming you have a 'timestamp' field in ChatMessage
        'avatar_url': user_profile.image.url if user_profile.image else '',  # Update accordingly
    }

    return JsonResponse(response_data, safe=False)
from django.core.serializers import serialize
def receive_message(request, slug):
    profile = get_object_or_404(Profile, slug=slug)
    user_profile = get_object_or_404(Profile, user=request.user)
    
    # arr =[]
    # Filter messages where the sender is the other user and the receiver is the current user
    msg_receiver = ChatMessage.objects.filter(
        Q(msg_sender=profile) & Q(msg_receiver=user_profile)
    ).order_by('send_in')
    serialized_messages = serialize('json', msg_receiver, fields=('send_in', 'body', 'msg_sender__image'))

    # Deserialize the data to manipulate the structure
    data = json.loads(serialized_messages)
    arr = []

    for entry in data:
        fields = entry['fields']
        send_in = fields.get('send_in', '')  # Get the timestamp or an empty string if not present

        # Build a dictionary with the desired structure
        message_data = {
            'body': fields.get('body', ''),
            'send_in': send_in,
            'avatar_url': profile.image.url if profile.image else '', 
        }

        arr.append(message_data)

    return JsonResponse(arr, safe=False)


def friend_request(request,slug):
    profile = get_object_or_404(Profile, user=request.user)
    friend_requests = profile.friend_request.all()
    return render(request,'chat/friend_request_list.html',{'friend_requests': friend_requests})


def add_friend(request):
    user_profile = get_object_or_404(Profile, user=request.user)
    friend=user_profile.friend.all()
    add_friends = Friend.objects.all().exclude(profile=request.user.profile)
    return render(request,'chat/add_friend.html',{'add_friends': add_friends})

def send_request(request,slug):
    if request.user.is_authenticated:
        user_profile = get_object_or_404(Profile, user=request.user)
        profile=get_object_or_404(Profile,slug=slug)
        profile.friend_request.add(user_profile.friend_profile)
        profile.save()
    return redirect('/add_friend/')


def accecpt_friend_request(request,slug):
    if request.user.is_authenticated:
        user_profile = get_object_or_404(Profile, user=request.user)
        profile=get_object_or_404(Profile,slug=slug)
        profile.friend.add(user_profile.friend_profile)
        user_profile.friend.add(profile.friend_profile)
        user_profile.friend_request.remove(profile.friend_profile)
        user_profile.save()
        profile.save()
    return redirect('/')

chat/templates/chat/add_friend.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">


    <title>bs4 beta friend list - Bootdey.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
        body {
            margin-top: 20px;
            background: #FAFAFA;
        }

        /*==================================================
  Nearby People CSS
  ==================================================*/

        .people-nearby .google-maps {
            background: #f8f8f8;
            border-radius: 4px;
            border: 1px solid #f1f2f2;
            padding: 20px;
            margin-bottom: 20px;
        }

        .people-nearby .google-maps .map {
            height: 300px;
            width: 100%;
            border: none;
        }

        .people-nearby .nearby-user {
            padding: 20px 0;
            border-top: 1px solid #f1f2f2;
            border-bottom: 1px solid #f1f2f2;
            margin-bottom: 20px;
        }

        img.profile-photo-lg {
            height: 80px;
            width: 80px;
            border-radius: 50%;
        }
    </style>
</head>

<body>
    <div style="    border-bottom: 1px solid;
    padding-bottom: 6px;justify-content: center;
    display: flex;">
        <h3 class="text-muted prj-name">
            <span"><a href="/" style="font-size: 30px;
            font-weight: 900;
            margin-bottom: 13px;
            color: white;
            background: #4b00ff;
            border-radius: 50%;
            padding: 6px;
            text-align: center;
            text-decoration:none;
            margin-right: 11px;" class="ks-amount">
                < </a></span>
            <span class="fa fa-users fa-2x principal-title"></span>
            Add Friend
        </h3>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-11">
                <div class="people-nearby">
                    {% for friend in add_friends %}
                        <div class="nearby-user">
                            <div class="row" style="justify-content: center;">
                                <div class="col-md-1 col-sm-2" style="margin-right: 20px;">
                                    {% if friend.profile.image %}
                                        <img src="{{ friend.profile.image.url }}" alt="user"
                                        class="profile-photo-lg" width="40" height="40">
                                    {% else %}
                                        <img src="{% static 'user_no_image.png' %}" alt="user"
                                        class="profile-photo-lg" width="40" height="40">
                                    {% endif %}
                                </div>
                                <div class="col-md-3 col-sm-3">
                                    <h5><a href="#" class="profile-link">{{ friend.profile.user.first_name }} {{ friend.profile.user.last_name }}</a></h5>
                                    <p name="user_name" >@ {{friend.profile.user.username }}</p>
                                    <p class="text-muted">25 mutual friends</p>
                                </div>
                                <div class="col-md-2 col-sm-2">
                                    <a href="{% url 'chat:send_request' slug=friend.profile.slug%}" class="btn btn-primary pull-right">Add Friend</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
    <script type="text/javascript">

    </script>
</body>

</html>

chat/templates/chat/chat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">


    <title>white chat - Bootdey.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
        body {
            margin-top: 20px;
        }

        .chat-online {
            color: #34ce57
        }

        .chat-offline {
            color: #e4606d
        }

        .chat-messages {
            display: flex;
            flex-direction: column;
            max-height: 800px;
            overflow-y: scroll
        }

        .chat-message-left,
        .chat-message-right {
            display: flex;
            flex-shrink: 0
        }

        .chat-message-left {
            margin-right: auto
        }

        .chat-message-right {
            flex-direction: row-reverse;
            margin-left: auto
        }

        .py-3 {
            padding-top: 1rem !important;
            padding-bottom: 1rem !important;
        }

        .px-4 {
            padding-right: 1.5rem !important;
            padding-left: 1.5rem !important;
        }

        .flex-grow-0 {
            flex-grow: 0 !important;
        }

        .border-top {
            border-top: 1px solid #dee2e6 !important;
        }
        .card{
            border:none;
        }
        .border-right{
            border:none;
        }
        .border-120{
            border: 1px solid #000;
            border-radius: 12px;
            margin-top: 5px;
        }
    </style>
</head>

<body>
    <style>
        .list-group-item+.list-group-item {
            border-top-width: 1px;
        }
    </style>
    <main class="content">
        <div class="container p-0">
            <h1 class="h3 mb-3">Messages</h1>
            <p>Wellcome {{request.user}}</p>
            <a class="btn btn-primary" style="display: flex;align-items: center;text-decoration: none;    height: 30px;
            justify-content: end;
            width: 78px;
            background-color: red;
            border: none;" href="{% url 'accounts:log_out' %}" >Logout</a>
            <div style="    display: flex;align-items: center;
            justify-content: space-between;">

                <a class="btn btn-primary" style="display: flex;align-items: center;text-decoration: none;    height: 30px;
                justify-content: start;" href="{% url 'chat:add_friend' %}" >Add Friend</a>
                <a style="    display: flex;" href="{% url 'chat:friend_request' slug=profile.slug%}" ><img width="66" height="66" src="https://img.icons8.com/external-smashingstocks-flat-smashing-stocks/66/external-Friend-Request-notification-and-mailing-smashingstocks-flat-smashing-stocks.png" alt="external-Friend-Request-notification-and-mailing-smashingstocks-flat-smashing-stocks"/></a>
            </div>
            <div class="card">
                <div class="row g-0">
                    <div class="col-12 col-lg-12 col-xl-12 border-right">
                        <div class="px-4 d-none d-md-block">
                            <div class="d-flex align-items-center">
                                <div class="flex-grow-1">
                                    <input type="text" class="form-control my-3" placeholder="Search...">
                                </div>
                            </div>
                        </div>
                        {% for friend in friends  %}
                            <a href="{% url 'chat:chat_details' slug=friend.profile.slug%}"  class="list-group-item list-group-item-action border-120">
                                <div class="badge bg-success float-right">5</div>
                                <div class="d-flex align-items-start">
                                    {% if friend.profile.image %}
                                            <img src="{{ friend.profile.image.url }}" class="rounded-circle mr-1" alt="Vanessa Tucker" width="40" height="40">
                                    {% else %}
                                        <img src="{% static 'user_no_image.png' %}" class="rounded-circle mr-1" alt="Vanessa Tucker" width="40" height="40">
                                    {% endif %}
                                    <div class="flex-grow-1 ml-3">
                                        {{ friend.profile.user.first_name }} {{ friend.profile.user.last_name }}
                                        <div class="small"><span class="fas fa-circle chat-online"></span> Online</div>
                                    </div>
                                </div>
                            </a>
                        {% endfor %}
                        <hr class="d-block d-lg-none mt-1 mb-0">
                    </div>
                </div>
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript">

    </script>
</body>

</html>

chat/templates/chat/friend_request_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">


    <title>Friend Request user list - Bootdey.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
        .list-content {
            min-height: 300px;
        }

        .list-content .list-group .title {
            background: #5bc0de;
            border: 2px solid #DDDDDD;
            font-weight: bold;
            color: #FFFFFF;
        }

        .list-group-item img {
            height: 80px;
            width: 80px;
        }

        .jumbotron .btn {
            padding: 5px 5px !important;
            font-size: 12px !important;
        }

        .prj-name {
            color: #5bc0de;
        }

        .break {
            width: 100%;
            margin: 20px;
        }

        .name {
            color: #5bc0de;
        }
    </style>
</head>

<body>
    <link href="https://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
    <div class="container bootstrap snippets bootdey">
        <div class="header">
            <h3 class="text-muted prj-name">
                <span"><a href="/" style="font-size: 30px;
                font-weight: 900;
                margin-bottom: 13px;
                color: white;
                background: #4b00ff;
                border-radius: 50%;
                padding: 6px;
                text-align: center;
                text-decoration:none;
                margin-right: 11px;" class="ks-amount">
                    < </a></span>
                <span class="fa fa-users fa-2x principal-title"></span>
                Friend Request
            </h3>
        </div>
        <div class="jumbotron list-content">
            <ul class="list-group">
                <li href="#" class="list-group-item title">
                    Your Friend Request
                </li>
                {% for friend_request in friend_requests %}
                    <li href="#" class="list-group-item text-left">
                        {% if friend_request.profile.image %}
                            <img src="{{ friend_request.profile.image.url }}" class="img-thumbnail" alt="Vanessa Tucker" width="40" height="40">
                        {% else %}
                            <img src="{% static 'user_no_image.png' %}" class="img-thumbnail" alt="Vanessa Tucker" width="40" height="40">
                        {% endif %}
                        <label class="name">
                            {{ friend_request.profile.user.first_name }} {{ friend_request.profile.user.last_name }}<br>
                        </label>
                        <label class="pull-right">
                            <a class="btn btn-success btn-xs glyphicon glyphicon-ok" href="{% url 'chat:accecpt_friend_request' slug=friend_request.profile.slug%}" title="View"></a>
                            <a class="btn btn-danger  btn-xs glyphicon glyphicon-trash" href="#" title="Delete"></a>
                            <a class="btn btn-info  btn-xs glyphicon glyphicon glyphicon-comment" href="#"
                                title="Send message"></a>
                        </label>
                        <div class="break"></div>
                    </li>
                {% endfor %}
                
            </ul>
        </div>
    </div>
    </div>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script type="text/javascript">

    </script>
</body>

</html>

chat/templates/chat/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="no-js">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Venus Template</title>
	<link href="https://fonts.googleapis.com/css?family=Heebo:400,700|Oxygen:700" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'home.css' %}">
	<script src="https://unpkg.com/scrollreveal@4.0.5/dist/scrollreveal.min.js"></script>
</head>

<body class="is-boxed has-animations">
	<div class="body-wrap boxed-container">
		<header class="site-header text-light">
			<div class="container">
				<div class="site-header-inner">
					<div class="brand header-brand">
						<h1 class="m-0">
							<a href="#">
								<img class="header-logo-image" src="{% static 'logo.svg' %}" alt="Logo">
							</a>
						</h1>
					</div>
				</div>
			</div>
		</header>

		<main style="height: 100%;">
			<section class="hero text-center text-light">
				<div class="hero-bg" style="height: 100vh;"></div>
				<div class="hero-particles-container">
					<canvas id="hero-particles"></canvas>
				</div>
				<div class="container-sm">
					<div class="hero-inner">
						<div class="hero-copy">
							<h1 class="hero-title mt-0">Wellcome To ChatAPP</h1>
							<p class="hero-paragraph">Engoy using chat !!</p>
							<div class="hero-cta">
								<a class="button button-primary button-wide-mobile" href="{% url 'accounts:login' %}">Registration</a>
							</div>
						</div>
						<div class="mockup-container">
							<div class="mockup-bg">
								<img src="{% static 'iphone-hero-bg.svg' %}" alt="iPhone illustration">
							</div>
						</div>
					</div>
				</div>
			</section>



			<script src="{% static 'main.min.js' %}"></script>
</body>

</html>